name: Render CV and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  render-cv:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        continue-on-error: false

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install rendercv
      - name: Install rendercv
        run: pip install rendercv[full]

      # Step 5: Render CV
      - name: Render CV
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          rendercv render Bhavesh_Kakrotra_CV.yaml
        continue-on-error: false

      # Step 6: Upload CV as an artifact (using v2 instead of v3)
      - name: Upload CV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bhavesh_Kakrotra_CV
          path: rendercv_output/Bhavesh_Kakrotra_CV.pdf
        continue-on-error: false

      # Optional Step: Clean up
      - name: Clean up
        run: |
          echo "Cleanup if necessary"
        continue-on-error: true
